apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: maven
    image: maven:3.5.0
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/context/Dockerfile",
            "--context=/context",
 #           "--no-push",
            "--destination=eu.gcr.io/emea-sa-demo/test-kaniko:latest"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
      - name: context
        mountPath: /context
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
  - name: docker-gcr
    projected:
      sources:
      - secret:
          name: kaniko-secret
          items:
            - key: .dockerconfigjson
              path: config.json